# Generated by Django 5.0.4 on 2024-04-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciname', models.CharField(max_length=300, verbose_name='Mokslinis pavadinimas')),
                ('watering', models.CharField(max_length=30, verbose_name='Laistymas')),
                ('name', models.CharField(max_length=100, verbose_name='Vardas')),
            ],
        ),
    ]
