# Generated by Django 5.0.4 on 2024-04-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantwatering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pic',
            field=models.ImageField(null=True, upload_to='pics', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sciname',
            field=models.CharField(max_length=300, verbose_name='Scientific name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering',
            field=models.CharField(max_length=30, verbose_name='Watering'),
        ),
    ]
