# Generated by Django 5.0.4 on 2024-04-25 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantwatering', '0002_plant_pic_alter_plant_name_alter_plant_sciname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'Watered'), ('n', 'Needs watering'), ('d', 'Dry')], default='w', help_text='Watring status', max_length=1),
        ),
        migrations.AddField(
            model_name='plant',
            name='watered',
            field=models.DateField(blank=True, null=True, verbose_name='Last watered'),
        ),
    ]
