# Generated by Django 5.0.4 on 2024-04-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantwatering', '0003_plant_owner_plant_status_plant_watered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics', verbose_name='Picture'),
        ),
    ]
