# Generated by Django 5.0.4 on 2024-04-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantwatering', '0005_alter_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sciname',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Scientific name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Watering'),
        ),
    ]
