# Generated by Django 5.0.4 on 2024-04-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantwatering', '0006_alter_plant_sciname_alter_plant_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='next_watering',
            field=models.DateField(blank=True, null=True, verbose_name='Next watering'),
        ),
    ]
