# Generated by Django 5.0.4 on 2024-04-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantwatering', '0007_plant_next_watering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'Watered'), ('n', 'Needs watering'), ('d', 'Dry')], default='w', help_text='Watering status', max_length=1),
        ),
    ]
