# Generated by Django 5.0.4 on 2024-05-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantwatering', '0008_alter_plant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='status',
        ),
    ]
